#配置数据库
spring:
  main:
    allow-bean-definition-overriding: true
  datasource: 
    username: root  
    password: 123456  
    url: jdbc:mysql://localhost:3306/test?useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver 
#配置mybatis
mybatis:
   mapper-locations: classpath:mapper/*.xml
   type-aliases-package: edu.swjtuhc.demo.mapper



  
    